lib/bloggerday_web/router.ex
defmodule BloggerdayWeb.Router do
  use BloggerdayWeb, :router

  import BloggerdayWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BloggerdayWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BloggerdayWeb do
    pipe_through :browser

    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", BloggerdayWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BloggerdayWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", BloggerdayWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", BloggerdayWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", BloggerdayWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/bloggerday_web/controllers/user_session_controller.ex
defmodule BloggerdayWeb.UserSessionController do
  use BloggerdayWeb, :controller

  alias Bloggerday.Accounts
  alias BloggerdayWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      render(conn, "new.html", error_message: "Ungültige E-Mail Adresse oder Passwort.")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Sie sind abgemeldet.")
    |> UserAuth.log_out_user()
  end
end

lib/bloggerday_web/views/user_session_view.ex
defmodule BloggerdayWeb.UserSessionView do
  use BloggerdayWeb, :view
end

lib/bloggerday_web/templates/user_session/new.html.eex
<div class="min-h-screen bg-gray-50 flex flex-col py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
      Log in
    </h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">

    <%= form_for @conn, Routes.user_session_path(@conn, :create), [class: "space-y-6", as: :user], fn f -> %>
      <%= if @error_message do %>
        <div class="alert alert-danger">
          <p><%= @error_message %></p>
        </div>
      <% end %>

        <div>
          <label for="email" class="block text-sm font-medium text-gray-700">
            E-Mail Adresse
          </label>
          <div class="mt-1">
            <%= email_input f, :email, required: true, id: "email", type: "email", autofocus: "true", autocomplete: "email", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
          </div>
        </div>

        <div>
          <label for="password" class="block text-sm font-medium text-gray-700">
            Passwort
          </label>
          <div class="mt-1">
            <%= password_input f, :password, required: true, id: "password", type: "password", autocomplete: "new-password", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
          </div>
        </div>

        <div class="flex items-center justify-between">
          <div class="flex items-center">
            <%= checkbox f, :remember_me, class: "h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded" %>
            <label for="remember_me" class="ml-2 block text-sm text-gray-900">
              60 Tage eingeloggt bleiben
            </label>
          </div>

          <div class="text-sm">
            <%= link "Passwort vergessen?", to: Routes.user_reset_password_path(@conn, :new), class: "font-medium text-indigo-600 hover:text-indigo-500" %>
          </div>
        </div>

        <div>
          <%= submit "Anmelden", class: "w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
        </div>

    <% end %>

    </div>
  </div>
</div>